# This is a basic workflow to help you get started with Actions

name: CI & CD

# trigger
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

# pekerjaan yang dilakukan (ex : test, build, dll)
jobs:
  test:
  # ini adalah vm ubuntu
    runs-on: ubuntu-latest
    # steps berjalan secara urut/sequential
    steps:
      # 1. checkout untuk copy code ke proses ini
      - uses: actions/checkout@v3
      # 2. instal ruby
      - name: install ruby
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version: '3.0'
      - name: bundle install
        run: bundle install
          # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # 3. migrate
      - name: migration 🤫
        run: rails db:migrate
      # 4. testing (bundle exec rspec -fd)
      - name: Run rails test
        run: bundle exec rspec -fd

  build-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: login docker registry
        uses: azure/docker-login@v1
        with:
          login-server: dzbuild.azurecr.io
          username: S{{ secrets.acr_dzbuild_username }}
          password: ${{ secrets.acr_dzbuild_password }}
      - name: build image
        run: docker build -t pipelinedemoku.azurecr.io/final-project:latest .
      - name: push registry
        run: docker push pipelinedemoku.azurecr.io/final-project:latest
  
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - uses: actions/checkout@v3
      - name: deploy staging
        run: echo 'deploy staging'

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/head/master'
    steps:
      - uses: actions/checkout@v3
      - name: deploy production
        run: echo 'deploy production'

  send-telegram-group:
    runs-on: ubuntu-latest
    needs: deploy-to-production
    if: github.ref == 'refs/head/master'
    steps:
      - uses: actions/checkout@v3
      - name: send to tele group
        run: echo 'send to tele group'
    